[package]
name = "websocat"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/websocat.rs"

[dependencies]
clap = { workspace = true }
wasi_ext_lib = { workspace = true }
wasi = { workspace = true }
